### ISSUE TITLE
contributing: datepicker

### ISSUE THREAD

**Issue by horacimacias** [yewprint/yewprint#170]
I'm interested in this crate and would like to extend it to also support DatePicker https://blueprintjs.com/docs/#datetime/datepicker

Is there any guidance/document/suggestion for me to use as a starting point in order to develop this in a way that is more likely to be accepted?

**Comment by cecton** [comment]
Hello and welcome :wave: 

This crate is in early development and I don't personally have strong requirements.

You will probably need the Overlay which is already developed. You might also have a hard time with date time manipulation. Ideally you should not rely on chrono and use the browser's API to get all the information you need. If you do use external crates I might ask to keep the component behind a feature flag (but that's not a big deal).

In any case, even if it's not 100% to my taste it's okay, as long we start with something that works, I will be more than happy.

Another advice: don't bother too much with animations. I think it's more important to get the component working rather than get the animations perfect.

**Comment by horacimacias** [comment]
great, thanks for the tips. Let's see what I can come up with.
